pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                url: 'https://github.com/Angurajnagaraj/Jenkins-Zero-To-Hero/',
                branch: 'main'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    cd python-jenkins-argocd-k8s
                    echo 'Buid Docker Image'
                    docker build -t angurajnagaraj/cicd-e2e:${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    docker push angurajnagaraj/cicd-e2e:${BUILD_NUMBER}
                    '''
                }
            }
        }
        
        stage('Checkout K8S manifest SCM'){
            steps {
                url: 'https://github.com/Angurajnagaraj/cicd-demo-manifests-repo.git',
                branch: 'main'
            }
        }
        
    }
}
