pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'python:3.9.21-alpine3.21' }
      }
      steps {
        print('Hello World')
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
